
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: CakeBaking
   jobs:
     - job: StartingCakeBaking
   displayName: StartingCakeBaking

 - stage: BakingTin
   jobs:
     - job: BakingTin
   displayName: TakeBakingTin

 - stage: ReadyOven
   jobs:
     - job: ReadyOvenAt180
   displayName: ReadyOvenAt180

 - stage: Mixiture1
   dependsOn: ReadyOven
   jobs:
     - job: CocoaBakingPowderMaidaMixture
   displayName: CocoaBakingPowderMaidaMixture

 - stage: Mixiture2
   dependsOn: ReadyOven
   jobs:
     - job: ButterMilkmaidMixture
   displayName: ButterMilkmaidMixture

 - stage: CombineMixtureAndMixture2
   dependsOn:
   - Mixiture1
   - Mixiture2
   condition: and(succeeded('Mixiture1', 'Mixiture2'))
   jobs:
     - job: CombineMixtureAndMixture2
   displayName: CombineMixtureAndMixture2

 - stage: FinalStage
   dependsOn: CombineMixtureAndMixture2
   condition: failed('CombineMixtureAndMixture2')
   jobs:
     - job: PlaceInOvenForBaking
   displayName: PlaceInOvenForBaking