# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: SP
   jobs:
     - job: startingportal
   displayName: startingPortal

 - stage: A
   dependsOn: SP
   jobs:
     - job: StageComponentA
   displayName: Stage-Component-A

 - stage: B
   dependsOn: SP
   jobs:
     - job: StageComponentB
   displayName: Stage-Component-B


 - stage: C
   dependsOn: SP
   jobs:
     - job: StageComponentC
   displayName: Stage-Component-C

 - stage: PA
   dependsOn: 
   - A
   - B
   - C
   jobs:
     - job: ProductArtifact
   displayName: Product-Artifact

 - stage: DeployApp
   dependsOn: PA
   condition: succeeded('PA')
   jobs:
     - job: TestApp
   displayName: DeployApp

 - stage: RollingBack
   dependsOn: PA
   condition: failed('PA')
   jobs:
     - job: TestApp1
   displayName: RollingBack